### PR TITLE
Fix-Tag-Details-Ui

### LINKED ISSUE #135: Bug - Details text cut of when text wraps

### PR DESCRIPTION
**Pull request by tanyutao544**
# Summary
- Updates Tag colors to be more distinct
- Update Details Ui text to display completely when text wraps

## Files Changes
- Colors.java addition of new colors
- TagBox.java modify color selector to use new colors
- ApplicationListCard.fxml modify width parameters for details label

### CODE REVIEW

**Review by yongler — APPROVED** [review]

File: src/main/java/seedu/address/commons/util/Colors.java [hunk 1]
```diff
@@ -4,9 +4,11 @@
     public static final String RED = "-fx-background-color: #d10000;";
     public static final String GREY = "-fx-background-color: #808080;";
     public static final String GREEN = "-fx-background-color: #03c200;";
-    public static final String ORANGE = "-fx-background-color: #c49700;";
+    public static final String ORANGE = "-fx-background-color: #FC7903;";
```
Comment (yongler) [inline src/main/java/seedu/address/commons/util/Colors.java:7]: LGTM

**Review by yongler — APPROVED** [review]
