### PR TITLE
Bug - Fix sorting by interview 

### LINKED ISSUE #222: Bug - Sorting by Interview Slot not working
As per title

### PR DESCRIPTION
**Pull request by laughingkid-sg**
The interview sorting order was wrong.

Fix #222

### CODE REVIEW

**Review by tanyutao544 — APPROVED** [review]

File: src/main/java/seedu/address/logic/sort/InterviewSlotComparator.java [hunk 1]
```diff
@@ -16,7 +16,7 @@
     @Override
     public int compare(Application o1, Application o2) {
         LocalDateTime app1 = o1.getInterviewSlot().getValue();
-        LocalDateTime app2 = o1.getInterviewSlot().getValue();
+        LocalDateTime app2 = o2.getInterviewSlot().getValue();
```
Comment (lchokhoe) [inline src/main/java/seedu/address/logic/sort/InterviewSlotComparator.java:19]: Good catch!

**Review by lchokhoe — APPROVED** [review]
Good catch! LGTM.
