### PR TITLE
Bug - Fix interaction between `find` and `edit`

### LINKED ISSUE #200: Bug - Interaction between "find" and "edit" command
When using `find` followed by `edit` command, an unintended behavior occurs where the `edit` command causes the full application list to get shown.

This is an unintended behavior since it would be very distracting for users.

### PR DESCRIPTION
**Pull request by lchokhoe**
# Bug - Fix interaction between `find` and `edit`

## Key Summary
- Previously, if the user calls `find` then `edit`, the filtered application list would revert to the full application list.
- Now, the `edit` command will no longer revert back to the full application list and will instead recall the previously used filter.

## Other Things to Note
- If the user calls `find n/Grab` followed by `edit 1 n/Shopee` for example, the index 1 application in the list will disappear. This is intended as the index 1 application, whose name has changed to "Shopee", no longer fits the filter created by `find n/Grab`. The same logic applies to all prefixes that the `find` command accepts. This will be made known in the UG.

#### 1. EditCommand.java
- EditCommand#execute() now makes a call to updateFilteredApplicationList() without any arguments.

#### 2. Model.java
- Model#updateFilteredApplicationList() is now overloaded to also accept a variant without arguments.

#### 3. ModelManager.java
- Model#updateFilteredApplicationList() is now overloaded to also accept a variant without arguments. The override to this method has been implemented since ModelManager extends Model.
- currentFilter field created to store the predicate that was last used (one command ago) by the user.

#### 4. AddCommandTest.java
- AddCommandTest#ModelStub updated to override new overloaded Model#updateFilteredApplicationList() method.

#### 5. EditCommandTest.java
- EditCommandTest#execute_filteredList_success() modified to reset the currentFilter of the model to PREDICATE_SHOW_ALL_APPLICATIONS before executing the `edit` command.

## Feedback that I would like
I need help with the phrasing of the constraint mentioned in the "Other Things to Note" section.
Or any comments on whether the constraint is acceptable or not.

Ready for review @joszx @laughingkid-sg @yongler @tanyutao544 (anyone will do)

Implements #200

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -142,6 +145,12 @@ public void sortApplications(Comparator<Application> c, String orderBy) {
     public void updateFilteredApplicationList(Predicate<Application> predicate) {
         requireNonNull(predicate);
         filteredApplications.setPredicate(predicate);
+        this.currentFilter = predicate;
+    }
+
+    @Override
+    public void updateFilteredApplicationList() {
+        updateFilteredApplicationList(this.currentFilter);
```
Comment (joszx) [inline src/main/java/seedu/address/model/ModelManager.java:153]: Nice job implementing this! Changes minimal code whilst giving the desired behavior.

**Review by joszx — APPROVED** [review]
LGTM. As for the constraint mentioned in the "Other Things to Note" section, the phrasing seems alright to me. The constraint was definitely something I didn't consider but looking back now makes sense to have. Nice spot!
