### PR TITLE
Bug - Fix PED issues

### LINKED ISSUE #146: [PE-D] Cannot add 2 internships from the same company.
A user may have 2 applications to the same company for different positions, such as Software Engineer and QA Engineer. However, InternApply only allows 1 application per company.

Use case:

1. `add n/Shopee j/Software Engineer Intern p/87438807 e/hr@shopee.sg a/5 Science Park Dr, #06-40 ast/APPLIED`
2. `add n/Shopee j/QA Engineer Intern p/87438807 e/hr@shopee.sg a/5 Science Park Dr, #06-40 ast/APPLIED`

Output: `This application already exists in InternApply.`

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: TypeDefinition/ped#1

### LINKED ISSUE #150: [PE-D] Not clear when 2 applications are the same
Applications are considered the same even when job titles are different. So what if we apply for 2 different roles are the same company?

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: chanyijuan/ped#1

### LINKED ISSUE #152: [PE-D] Incorrect UI Screenshot in UG
The screenshot provided in the UG Quick Start does not match the actual UI of the application. The application has an additional third panel containing statistics of the applications. 

To reproduce, simply launch  the application.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: manu2002g/ped#1

### LINKED ISSUE #171: [PE-D] Email not checking for .com
Email not checking for .com could result in invalid email id.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: rahulprasad01/ped#8

### PR DESCRIPTION
**Pull request by joszx**
# Fix PED issues

## Key Summary
- Modified email regex to require top level domain, i.e. ".com", as well as relevant test cases
- Update main window and reminder window UI pictures in docs/images
- Define duplicate applications, applications with the same name, job title and optional tags are not allowed
- Update Add and edit commands to not allow duplicate applications
- Add and modify test cases related to duplicated applications

## Other Updates
- Images in UG and index.md now show the latest application UI
- Name, job title and optional tags are case insensitive i.e. application with same fields except name "grab" and "Grab" are considered 2 different applications
- Manually tested each add and edit command with respect to duplicate applications
- Update add and edit command duplicate applications error message
- All Automated tests passed 267/267

Fix #171, #152, #150, #146

### CODE REVIEW

File: src/main/java/seedu/address/model/application/Email.java [hunk 1]
```diff
@@ -20,15 +20,18 @@
...
     private static final String ALPHANUMERIC_NO_UNDERSCORE = "[^\\W_]+"; // alphanumeric characters except underscore
     private static final String LOCAL_PART_REGEX = "^" + ALPHANUMERIC_NO_UNDERSCORE + "([" + SPECIAL_CHARACTERS + "]"
             + ALPHANUMERIC_NO_UNDERSCORE + ")*";
     private static final String DOMAIN_PART_REGEX = ALPHANUMERIC_NO_UNDERSCORE
             + "(-" + ALPHANUMERIC_NO_UNDERSCORE + ")*";
     private static final String DOMAIN_LAST_PART_REGEX = "(" + DOMAIN_PART_REGEX + "){2,}$"; // At least two chars
-    private static final String DOMAIN_REGEX = "(" + DOMAIN_PART_REGEX + "\\.)*" + DOMAIN_LAST_PART_REGEX;
+    private static final String DOMAIN_MIDDLE_PART_REGEX = "(\\.*(" + DOMAIN_PART_REGEX + ")+)*\\."; // Multiple .co.in
+    private static final String DOMAIN_REGEX = "(" + DOMAIN_PART_REGEX + ")+" + DOMAIN_MIDDLE_PART_REGEX
+            + DOMAIN_LAST_PART_REGEX;
```
Comment (yongler) [inline src/main/java/seedu/address/model/application/Email.java:34]: Nice regex checking! 

This might be useful too: https://stackoverflow.com/questions/624581/what-is-the-best-java-email-address-validation-method, but as mentioned in the comments of the first post there might be some edge cases as well 

Other than the suggestion, LGTM!

**Review by yongler — APPROVED** [review]
