### PR TITLE
Bug - "edit" command now rejects empty TAG

### LINKED ISSUE #132: Bug - "edit" command wrongly accepts empty TAG
The "edit" command right now wrongly accepts empty "t/" inputs. This needs to be fixed since its a behavior that is inconsistent with the rest of the commands in SoC InternApply.

### PR DESCRIPTION
**Pull request by lchokhoe**
# Bug - "edit" command now rejects empty TAG

## Key Summary
- Previously, "edit" command still accepts "t/" as a valid input even though it's empty.
- Now, the "edit" command will correctly parse "t/" as an invalid input.

## Other Things to Note
- Previously, the EditCommandParserTest#parse_resetTags_success() test case was not changed despite the resetTag functionality it was testing for having been removed.
- The test case has been repurposed to parse_resetTags_failure() instead but this will need to be reviewed in a later iteration for relevance.

#### 1. ParserUtil.java
- ParserUtill#parseTags() will now check if the Collections<String> tags passed in as input is an empty Collections or not. This ensures that at instance of "t/" being inputted by the user will be treated as an invalid input.

#### 2. EditCommandParserTest.java
- EditCommandParserTest#parse_resetTags_success() is not longer a valid test case. It has been repurposed into parse_resetTags_failure() but the relevance of this test case will be reviewed in a later iteration.

## Feedback that I would like
If you can test that the bug is fixed that would be great. 

Ready for review @joszx @laughingkid-sg @yongler @tanyutao544 (anyone will do)

Implements #132

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -214,6 +215,9 @@ public static Tag parsePriorityTag(String tag) throws ParseException {
      */
     public static Set<Tag> parseTags(Collection<String> tags) throws ParseException {
         requireNonNull(tags);
+        if (tags.equals(Collections.emptySet())) {
```
Comment (laughingkid-sg) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:218]: Great use of ParseException.

File: src/test/java/seedu/address/logic/parser/EditCommandParserTest.java [hunk 2]
```diff
@@ -115,6 +115,17 @@ public void parse_invalidValue_failure() {
                 Name.MESSAGE_CONSTRAINTS);
     }
 
+    @Test
+    public void parse_resetTags_failure() {
```
Comment (laughingkid-sg) [inline src/test/java/seedu/address/logic/parser/EditCommandParserTest.java:119]: Well done! LGTM!

**Review by laughingkid-sg — APPROVED** [review]
