### PR TITLE
Fix issues with invalid date

### LINKED ISSUE #185: [PE-D] edit /idt command bug
Certain invalid date times are accepted by the command without producing an error message.

To reproduce: 
Run "edit 10 idt/31-02-2022 13:45"
The application creates an interview with a modified date 28 Feb 2022 instead of producing an error.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: manu2002g/ped#9

### PR DESCRIPTION
**Pull request by laughingkid-sg**
- Fixed issues with issues such as 29 Feb during non-leap years, as well as other invalid values such as 30 and 31 Feb
- Fix issues with calendar months without 31

Fixes #185  and #101

### CODE REVIEW

File: src/main/java/seedu/address/model/application/InterviewSlot.java [hunk 1]
```diff
@@ -6,13 +6,15 @@
...
+import java.time.format.ResolverStyle;
+
 /**
  * Represents the interview date and time of an Application in InternApply.
  */
 
 public class InterviewSlot {
 
-    public static final String FORMAT_DATETIME_INPUT = "dd-MM-yyyy HH:mm";
+    public static final String FORMAT_DATETIME_INPUT = "dd-MM-uuuu HH:mm";
```
Comment (yongler) [inline src/main/java/seedu/address/model/application/InterviewSlot.java:17]: LGTM!

File: src/main/java/seedu/address/model/application/InterviewSlot.java [hunk 2]
```diff
@@ -112,6 +112,7 @@ public int hashCode() {
     }
 
     private static LocalDateTime toLocalDateTime(String input) {
-        return LocalDateTime.parse(input, DateTimeFormatter.ofPattern(FORMAT_DATETIME_INPUT));
+        return LocalDateTime.parse(input, DateTimeFormatter.ofPattern(FORMAT_DATETIME_INPUT)
+                .withResolverStyle(ResolverStyle.STRICT));
```
Comment (yongler) [inline src/main/java/seedu/address/model/application/InterviewSlot.java:116]: Nice usage of this built in method

**Review by yongler — APPROVED** [review]
