### PR TITLE
Fix Interview sorting to include time factor

### LINKED ISSUE #176: [PE-D] List by interview wrong time order
List by interview resulting wrong time order. As for meetings on same day , those with time later later is listed first . As in the given example 2 meetings on the same day 08-04-2022. The one starting on 13:00 is listed before the one starting on 11:00

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: rahulprasad01/ped#9

### PR DESCRIPTION
**Pull request by laughingkid-sg**
Comparator for InterviewSlot will now ise `isAfter()` and `isBefore()` instead of default java comparator. 

Fix #176

### CODE REVIEW

File: src/main/java/seedu/address/logic/sort/InterviewSlotComparator.java [hunk 1]
```diff
@@ -14,7 +15,15 @@
      * */
     @Override
     public int compare(Application o1, Application o2) {
-        return o1.getInterviewSlot().getValue().compareTo(o2.getInterviewSlot().getValue());
+        LocalDateTime app1 = o1.getInterviewSlot().getValue();
+        LocalDateTime app2 = o1.getInterviewSlot().getValue();
+        if (app1.isAfter(app2)) {
+            return 1;
+        } else if (app1.isBefore(app2)) {
+            return -1;
```
Comment (yongler) [inline src/main/java/seedu/address/logic/sort/InterviewSlotComparator.java:23]: LGTM

**Review by yongler — APPROVED** [review]
