### PR TITLE
Bug - Reverse order for sorting priority

### LINKED ISSUE #154: [PE-D] Listing by priority in ascending order
Listing by priority in ascending order is listing from priority high to low. I think it will be more intuitive to list from low to high as it is in ascending order.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: rahulprasad01/ped#2

### PR DESCRIPTION
**Pull request by laughingkid-sg**
Reverse order for sorting priority

New sorting order ascending - `<no-tag>`, `low`, `medium`, `high`

Fixes #154

### CODE REVIEW

File: src/main/java/seedu/address/model/tag/PriorityTagType.java [hunk 1]
```diff
@@ -7,7 +7,17 @@
  * A public enumeration class for priority tags.
  */
 public enum PriorityTagType {
-    HIGH, MEDIUM, LOW;
+    HIGH(3), MEDIUM(2), LOW(1);
```
Comment (yongler) [inline src/main/java/seedu/address/model/tag/PriorityTagType.java:10]: LGTM

**Review by yongler — APPROVED** [review]
